language: go

go:
  - "1.12.x"

branches:
  only:
  - master
  - dev.master

env:
- GO111MODULE=on

services:
- redis-server

addons:
  hosts:
  - local

before_install:
- pwd

install:
- cat /etc/hosts

script:
- GOARCH=386 go test -v ./...
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)



